title: isyundong.com
author: Yundong Zhang
job: Software Engineer

home_author_destination: |
  Hi ðŸ‘‹ Iâ€™m Yundong, a software engineer, bug maker, professional daydreamer, and minimalist based in Hangzhou, China.

  I develop things as a Fullstack Software Engineer at Starblink. Previously, I worked as a Senior Backend Software Engineer at Xingyue Group, a Senior Backend Software Engineer at Bestdealer, and a Recommendation System Engineer at Klarna.



navigation_bars:
  - title: Home
    url: "home"
    icon: sparkles
  - title: Writing
    url: "writing"
    icon: pencil-line
#  - title: Journey
#    url: "journey"
#    icon: navigation
#  - title: Stack
#    url: "stack"
#    icon: wand-sparkles
  - title: Bookmarks
    url: "bookmarks"
    icon: bookmark

